# Generated by Django 2.0.7 on 2018-08-13 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
