# Generated by Django 2.0.7 on 2018-08-18 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_temp_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
