# Generated by Django 2.0.7 on 2018-08-18 06:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('authur', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Snap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('name', models.TextField(default='', max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('caption', models.CharField(default=models.TextField(default='', max_length=20), max_length=30)),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('authur', models.CharField(default='', max_length=30)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), default=[], size=None)),
                ('album', models.ManyToManyField(related_name='album_snaps', to='snaps.Album')),
            ],
        ),
    ]
