# Generated by Django 2.0.7 on 2018-07-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField()),
                ('caption', models.CharField(max_length=20)),
                ('likes', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
