# Generated by Django 2.0.7 on 2018-07-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pic',
            new_name='Snap',
        ),
    ]
