# Generated by Django 2.0.7 on 2018-08-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0002_auto_20180729_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='snap',
            name='album',
            field=models.CharField(default='General upload', max_length=20),
        ),
        migrations.AddField(
            model_name='snap',
            name='name',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='snap',
            name='caption',
            field=models.CharField(default=models.TextField(default='', max_length=20), max_length=20),
        ),
    ]
