# Generated by Django 2.0.7 on 2018-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0002_auto_20180825_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='snap',
            name='album',
            field=models.ManyToManyField(related_name='album_snaps', to='snaps.Album'),
        ),
    ]
