# Generated by Django 2.0.7 on 2018-08-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0004_remove_snap_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snap',
            name='image',
            field=models.ImageField(default='images/404.jpg', null=True, upload_to='images/'),
        ),
    ]
